name: example
description: Charts-Flutter Demo
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.1.1
  intl: ^0.19.0
flutter:
  uses-material-design: true
